# Copyright (C) 2025 Sanka1610
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true
cli-source = "MorpheApp/morphe-cli"
patches-source = "anddea/revanced-patches"
rv-brand = "RVX"
enable-magisk-update = true

[YouTube]
build-mode = "both"
version = "auto"
excluded-patches = ""
included-patches = " 'MaterialYou' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
module-prop-name = "RVX-by-anddea"
arch = "arm64-v8a"

[YouTube-Latest]
build-mode = "both"
version = "20.13.41"
excluded-patches = ""
included-patches = " 'MaterialYou' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
module-prop-name = "RVX-by-anddea-Latest"
arch = "arm64-v8a"

[Music]
build-mode = "both"
version = "auto"
excluded-patches = ""
included-patches = " 'MaterialYou' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
module-prop-name = "RVX-Music-by-anddea"
arch = "arm64-v8a"