parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true
patches-source = "anddea/revanced-patches"
rv-brand = "RVX"
enable-magisk-update = true

[YouTube]
build-mode = "both"
version = "auto"
excluded-patches = ""
included-patches = " 'MaterialYou' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "RVX-anddea"
arch = "arm64-v8a"

[YouTube-Latest]
build-mode = "both"
version = "20.13.41"
excluded-patches = ""
included-patches = " 'MaterialYou' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "RVX-anddea-Latest"
arch = "arm64-v8a"

[Music]
build-mode = "both"
version = "auto"
excluded-patches = ""
included-patches = " 'MaterialYou' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "RVX-Music-anddea"
arch = "arm64-v8a"
